//Verilog generated by VPR 0.0.0+16bf4bf5-dirty from post-place-and-route implementation
module counter (
    input \clk ,
    input \rst ,
    output \q[0] ,
    output \q[1] ,
    output \q[2] ,
    output \q[3] ,
    output \q[4] ,
    output \q[5] ,
    output \q[6] ,
    output \q[7] 
);

    //Wires
    wire \clk_output_0_0 ;
    wire \rst_output_0_0 ;
    wire \latch_q[0]_output_0_0 ;
    wire \latch_q[1]_output_0_0 ;
    wire \latch_q[2]_output_0_0 ;
    wire \latch_q[3]_output_0_0 ;
    wire \latch_q[4]_output_0_0 ;
    wire \latch_q[5]_output_0_0 ;
    wire \latch_q[6]_output_0_0 ;
    wire \latch_q[7]_output_0_0 ;
    wire \lut_n22_output_0_0 ;
    wire \lut_n26_output_0_0 ;
    wire \lut_n30_output_0_0 ;
    wire \lut_n34_output_0_0 ;
    wire \lut_n38_output_0_0 ;
    wire \lut_n42_output_0_0 ;
    wire \lut_n46_output_0_0 ;
    wire \lut_n50_output_0_0 ;
    wire \lut_$abc$215$new_n23__output_0_0 ;
    wire \lut_$abc$215$new_n25__output_0_0 ;
    wire \lut_$abc$215$new_n28__output_0_0 ;
    wire \lut_$abc$215$new_n30__output_0_0 ;
    wire \latch_q[6]_clock_0_0 ;
    wire \latch_q[0]_clock_0_0 ;
    wire \latch_q[1]_clock_0_0 ;
    wire \latch_q[2]_clock_0_0 ;
    wire \latch_q[3]_clock_0_0 ;
    wire \latch_q[4]_clock_0_0 ;
    wire \latch_q[5]_clock_0_0 ;
    wire \latch_q[7]_clock_0_0 ;
    wire \lut_n26_input_0_1 ;
    wire \lut_n34_input_0_0 ;
    wire \lut_n38_input_0_0 ;
    wire \lut_n42_input_0_0 ;
    wire \lut_n46_input_0_0 ;
    wire \lut_n50_input_0_0 ;
    wire \lut_n22_input_0_3 ;
    wire \lut_n30_input_0_1 ;
    wire \lut_n34_input_0_2 ;
    wire \lut_n38_input_0_2 ;
    wire \lut_n42_input_0_2 ;
    wire \lut_$abc$215$new_n25__input_0_1 ;
    wire \lut_$abc$215$new_n23__input_0_0 ;
    wire \q[0]_input_0_0 ;
    wire \lut_n38_input_0_1 ;
    wire \lut_n42_input_0_1 ;
    wire \lut_$abc$215$new_n25__input_0_0 ;
    wire \lut_$abc$215$new_n23__input_0_1 ;
    wire \q[1]_input_0_0 ;
    wire \lut_n42_input_0_3 ;
    wire \lut_$abc$215$new_n25__input_0_2 ;
    wire \lut_$abc$215$new_n23__input_0_2 ;
    wire \q[2]_input_0_0 ;
    wire \lut_n46_input_0_1 ;
    wire \lut_$abc$215$new_n25__input_0_3 ;
    wire \q[3]_input_0_0 ;
    wire \lut_$abc$215$new_n28__input_0_2 ;
    wire \lut_n50_input_0_1 ;
    wire \lut_n22_input_0_0 ;
    wire \lut_$abc$215$new_n30__input_0_0 ;
    wire \q[4]_input_0_0 ;
    wire \lut_$abc$215$new_n28__input_0_1 ;
    wire \lut_n22_input_0_1 ;
    wire \lut_$abc$215$new_n30__input_0_3 ;
    wire \q[5]_input_0_0 ;
    wire \lut_n26_input_0_2 ;
    wire \lut_$abc$215$new_n30__input_0_2 ;
    wire \q[6]_input_0_0 ;
    wire \lut_n30_input_0_2 ;
    wire \q[7]_input_0_0 ;
    wire \latch_q[5]_input_0_0 ;
    wire \latch_q[6]_input_0_0 ;
    wire \latch_q[7]_input_0_0 ;
    wire \latch_q[0]_input_0_0 ;
    wire \latch_q[1]_input_0_0 ;
    wire \latch_q[2]_input_0_0 ;
    wire \latch_q[3]_input_0_0 ;
    wire \latch_q[4]_input_0_0 ;
    wire \lut_n46_input_0_2 ;
    wire \lut_$abc$215$new_n28__input_0_0 ;
    wire \lut_n50_input_0_2 ;
    wire \lut_n22_input_0_2 ;
    wire \lut_$abc$215$new_n30__input_0_1 ;
    wire \lut_n26_input_0_0 ;
    wire \lut_n30_input_0_0 ;

    //IO assignments
    assign \q[0]  = \q[0]_input_0_0 ;
    assign \q[1]  = \q[1]_input_0_0 ;
    assign \q[2]  = \q[2]_input_0_0 ;
    assign \q[3]  = \q[3]_input_0_0 ;
    assign \q[4]  = \q[4]_input_0_0 ;
    assign \q[5]  = \q[5]_input_0_0 ;
    assign \q[6]  = \q[6]_input_0_0 ;
    assign \q[7]  = \q[7]_input_0_0 ;
    assign \clk_output_0_0  = \clk ;
    assign \rst_output_0_0  = \rst ;

    //Interconnect
    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[6]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[6]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[0]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[1]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[2]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[2]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[3]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[3]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[4]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[4]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[5]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[5]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clk_output_0_0_to_latch_q[7]_clock_0_0  (
        .datain(\clk_output_0_0 ),
        .dataout(\latch_q[7]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n26_input_0_1  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n26_input_0_1 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n34_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n34_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n38_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n38_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n42_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n42_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n46_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n46_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n50_input_0_0  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n50_input_0_0 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n22_input_0_3  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n22_input_0_3 )
    );

    fpga_interconnect \routing_segment_rst_output_0_0_to_lut_n30_input_0_1  (
        .datain(\rst_output_0_0 ),
        .dataout(\lut_n30_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_lut_n34_input_0_2  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\lut_n34_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_lut_n38_input_0_2  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\lut_n38_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_lut_n42_input_0_2  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\lut_n42_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_lut_$abc$215$new_n25__input_0_1  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n25__input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_lut_$abc$215$new_n23__input_0_0  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n23__input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[0]_output_0_0_to_q[0]_input_0_0  (
        .datain(\latch_q[0]_output_0_0 ),
        .dataout(\q[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[1]_output_0_0_to_lut_n38_input_0_1  (
        .datain(\latch_q[1]_output_0_0 ),
        .dataout(\lut_n38_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[1]_output_0_0_to_lut_n42_input_0_1  (
        .datain(\latch_q[1]_output_0_0 ),
        .dataout(\lut_n42_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[1]_output_0_0_to_lut_$abc$215$new_n25__input_0_0  (
        .datain(\latch_q[1]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n25__input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[1]_output_0_0_to_lut_$abc$215$new_n23__input_0_1  (
        .datain(\latch_q[1]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n23__input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[1]_output_0_0_to_q[1]_input_0_0  (
        .datain(\latch_q[1]_output_0_0 ),
        .dataout(\q[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[2]_output_0_0_to_lut_n42_input_0_3  (
        .datain(\latch_q[2]_output_0_0 ),
        .dataout(\lut_n42_input_0_3 )
    );

    fpga_interconnect \routing_segment_latch_q[2]_output_0_0_to_lut_$abc$215$new_n25__input_0_2  (
        .datain(\latch_q[2]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n25__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[2]_output_0_0_to_lut_$abc$215$new_n23__input_0_2  (
        .datain(\latch_q[2]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n23__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[2]_output_0_0_to_q[2]_input_0_0  (
        .datain(\latch_q[2]_output_0_0 ),
        .dataout(\q[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[3]_output_0_0_to_lut_n46_input_0_1  (
        .datain(\latch_q[3]_output_0_0 ),
        .dataout(\lut_n46_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[3]_output_0_0_to_lut_$abc$215$new_n25__input_0_3  (
        .datain(\latch_q[3]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n25__input_0_3 )
    );

    fpga_interconnect \routing_segment_latch_q[3]_output_0_0_to_q[3]_input_0_0  (
        .datain(\latch_q[3]_output_0_0 ),
        .dataout(\q[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[4]_output_0_0_to_lut_$abc$215$new_n28__input_0_2  (
        .datain(\latch_q[4]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n28__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[4]_output_0_0_to_lut_n50_input_0_1  (
        .datain(\latch_q[4]_output_0_0 ),
        .dataout(\lut_n50_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[4]_output_0_0_to_lut_n22_input_0_0  (
        .datain(\latch_q[4]_output_0_0 ),
        .dataout(\lut_n22_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[4]_output_0_0_to_lut_$abc$215$new_n30__input_0_0  (
        .datain(\latch_q[4]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n30__input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[4]_output_0_0_to_q[4]_input_0_0  (
        .datain(\latch_q[4]_output_0_0 ),
        .dataout(\q[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[5]_output_0_0_to_lut_$abc$215$new_n28__input_0_1  (
        .datain(\latch_q[5]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n28__input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[5]_output_0_0_to_lut_n22_input_0_1  (
        .datain(\latch_q[5]_output_0_0 ),
        .dataout(\lut_n22_input_0_1 )
    );

    fpga_interconnect \routing_segment_latch_q[5]_output_0_0_to_lut_$abc$215$new_n30__input_0_3  (
        .datain(\latch_q[5]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n30__input_0_3 )
    );

    fpga_interconnect \routing_segment_latch_q[5]_output_0_0_to_q[5]_input_0_0  (
        .datain(\latch_q[5]_output_0_0 ),
        .dataout(\q[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[6]_output_0_0_to_lut_n26_input_0_2  (
        .datain(\latch_q[6]_output_0_0 ),
        .dataout(\lut_n26_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[6]_output_0_0_to_lut_$abc$215$new_n30__input_0_2  (
        .datain(\latch_q[6]_output_0_0 ),
        .dataout(\lut_$abc$215$new_n30__input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[6]_output_0_0_to_q[6]_input_0_0  (
        .datain(\latch_q[6]_output_0_0 ),
        .dataout(\q[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_latch_q[7]_output_0_0_to_lut_n30_input_0_2  (
        .datain(\latch_q[7]_output_0_0 ),
        .dataout(\lut_n30_input_0_2 )
    );

    fpga_interconnect \routing_segment_latch_q[7]_output_0_0_to_q[7]_input_0_0  (
        .datain(\latch_q[7]_output_0_0 ),
        .dataout(\q[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n22_output_0_0_to_latch_q[5]_input_0_0  (
        .datain(\lut_n22_output_0_0 ),
        .dataout(\latch_q[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n26_output_0_0_to_latch_q[6]_input_0_0  (
        .datain(\lut_n26_output_0_0 ),
        .dataout(\latch_q[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n30_output_0_0_to_latch_q[7]_input_0_0  (
        .datain(\lut_n30_output_0_0 ),
        .dataout(\latch_q[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n34_output_0_0_to_latch_q[0]_input_0_0  (
        .datain(\lut_n34_output_0_0 ),
        .dataout(\latch_q[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n38_output_0_0_to_latch_q[1]_input_0_0  (
        .datain(\lut_n38_output_0_0 ),
        .dataout(\latch_q[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n42_output_0_0_to_latch_q[2]_input_0_0  (
        .datain(\lut_n42_output_0_0 ),
        .dataout(\latch_q[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n46_output_0_0_to_latch_q[3]_input_0_0  (
        .datain(\lut_n46_output_0_0 ),
        .dataout(\latch_q[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_n50_output_0_0_to_latch_q[4]_input_0_0  (
        .datain(\lut_n50_output_0_0 ),
        .dataout(\latch_q[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n23__output_0_0_to_lut_n46_input_0_2  (
        .datain(\lut_$abc$215$new_n23__output_0_0 ),
        .dataout(\lut_n46_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n25__output_0_0_to_lut_$abc$215$new_n28__input_0_0  (
        .datain(\lut_$abc$215$new_n25__output_0_0 ),
        .dataout(\lut_$abc$215$new_n28__input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n25__output_0_0_to_lut_n50_input_0_2  (
        .datain(\lut_$abc$215$new_n25__output_0_0 ),
        .dataout(\lut_n50_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n25__output_0_0_to_lut_n22_input_0_2  (
        .datain(\lut_$abc$215$new_n25__output_0_0 ),
        .dataout(\lut_n22_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n25__output_0_0_to_lut_$abc$215$new_n30__input_0_1  (
        .datain(\lut_$abc$215$new_n25__output_0_0 ),
        .dataout(\lut_$abc$215$new_n30__input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n28__output_0_0_to_lut_n26_input_0_0  (
        .datain(\lut_$abc$215$new_n28__output_0_0 ),
        .dataout(\lut_n26_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$215$new_n30__output_0_0_to_lut_n30_input_0_0  (
        .datain(\lut_$abc$215$new_n30__output_0_0 ),
        .dataout(\lut_n30_input_0_0 )
    );


    //Cell instances
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010010)
    ) \lut_n26  (
        .in({
            \lut_n26_input_0_2 ,
            \lut_n26_input_0_1 ,
            \lut_n26_input_0_0 }),
        .out(\lut_n26_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[6]  (
        .D(\latch_q[6]_input_0_0 ), 
        .Q(\latch_q[6]_output_0_0 ), 
        .clock(\latch_q[6]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10000000)
    ) \lut_$abc$215$new_n28_  (
        .in({
            \lut_$abc$215$new_n28__input_0_2 ,
            \lut_$abc$215$new_n28__input_0_1 ,
            \lut_$abc$215$new_n28__input_0_0 }),
        .out(\lut_$abc$215$new_n28__output_0_0 )
    );

    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00000001)
    ) \lut_n34  (
        .in({
            \lut_n34_input_0_2 ,
            1'b0,
            \lut_n34_input_0_0 }),
        .out(\lut_n34_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[0]  (
        .D(\latch_q[0]_input_0_0 ), 
        .Q(\latch_q[0]_output_0_0 ), 
        .clock(\latch_q[0]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010100)
    ) \lut_n38  (
        .in({
            \lut_n38_input_0_2 ,
            \lut_n38_input_0_1 ,
            \lut_n38_input_0_0 }),
        .out(\lut_n38_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[1]  (
        .D(\latch_q[1]_input_0_0 ), 
        .Q(\latch_q[1]_output_0_0 ), 
        .clock(\latch_q[1]_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0001010101000000)
    ) \lut_n42  (
        .in({
            \lut_n42_input_0_3 ,
            \lut_n42_input_0_2 ,
            \lut_n42_input_0_1 ,
            \lut_n42_input_0_0 }),
        .out(\lut_n42_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[2]  (
        .D(\latch_q[2]_input_0_0 ), 
        .Q(\latch_q[2]_output_0_0 ), 
        .clock(\latch_q[2]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010100)
    ) \lut_n46  (
        .in({
            \lut_n46_input_0_2 ,
            \lut_n46_input_0_1 ,
            \lut_n46_input_0_0 }),
        .out(\lut_n46_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[3]  (
        .D(\latch_q[3]_input_0_0 ), 
        .Q(\latch_q[3]_output_0_0 ), 
        .clock(\latch_q[3]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010100)
    ) \lut_n50  (
        .in({
            \lut_n50_input_0_2 ,
            \lut_n50_input_0_1 ,
            \lut_n50_input_0_0 }),
        .out(\lut_n50_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[4]  (
        .D(\latch_q[4]_input_0_0 ), 
        .Q(\latch_q[4]_output_0_0 ), 
        .clock(\latch_q[4]_clock_0_0 )
    );
    LUT_K #(
        .K(4),
        .LUT_MASK(16'b1000000000000000)
    ) \lut_$abc$215$new_n25_  (
        .in({
            \lut_$abc$215$new_n25__input_0_3 ,
            \lut_$abc$215$new_n25__input_0_2 ,
            \lut_$abc$215$new_n25__input_0_1 ,
            \lut_$abc$215$new_n25__input_0_0 }),
        .out(\lut_$abc$215$new_n25__output_0_0 )
    );

    LUT_K #(
        .K(4),
        .LUT_MASK(16'b0000000001101100)
    ) \lut_n22  (
        .in({
            \lut_n22_input_0_3 ,
            \lut_n22_input_0_2 ,
            \lut_n22_input_0_1 ,
            \lut_n22_input_0_0 }),
        .out(\lut_n22_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[5]  (
        .D(\latch_q[5]_input_0_0 ), 
        .Q(\latch_q[5]_output_0_0 ), 
        .clock(\latch_q[5]_clock_0_0 )
    );
    LUT_K #(
        .K(3),
        .LUT_MASK(8'b10000000)
    ) \lut_$abc$215$new_n23_  (
        .in({
            \lut_$abc$215$new_n23__input_0_2 ,
            \lut_$abc$215$new_n23__input_0_1 ,
            \lut_$abc$215$new_n23__input_0_0 }),
        .out(\lut_$abc$215$new_n23__output_0_0 )
    );

    LUT_K #(
        .K(4),
        .LUT_MASK(16'b1000000000000000)
    ) \lut_$abc$215$new_n30_  (
        .in({
            \lut_$abc$215$new_n30__input_0_3 ,
            \lut_$abc$215$new_n30__input_0_2 ,
            \lut_$abc$215$new_n30__input_0_1 ,
            \lut_$abc$215$new_n30__input_0_0 }),
        .out(\lut_$abc$215$new_n30__output_0_0 )
    );

    LUT_K #(
        .K(3),
        .LUT_MASK(8'b00010010)
    ) \lut_n30  (
        .in({
            \lut_n30_input_0_2 ,
            \lut_n30_input_0_1 ,
            \lut_n30_input_0_0 }),
        .out(\lut_n30_output_0_0 )
    );

    DFF #(
        .INITIAL_VALUE(1'b0)
    ) \latch_q[7]  (
        .D(\latch_q[7]_input_0_0 ), 
        .Q(\latch_q[7]_output_0_0 ), 
        .clock(\latch_q[7]_clock_0_0 )
    );

endmodule
